<a href="https://colab.research.google.com/github/Carinaaa/ML-Learning-Path/blob/intro-sklearn/Sklearn_less_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Regression Model evaluation

Link to docs: https://scikit-learn.org/stable/modules/model_evaluation.html#regression-metrics

The ones covered in this collab:

1. R^2 r-squared or coefficient of determination
2. Mean absolute error (MAE)
3. Mean squared error (MSE)

#### Fetch data

In [4]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [5]:
import pandas as pd
housing_df = pd.DataFrame(housing['data'], columns=housing['feature_names'])
housing_df['target'] = housing['target']
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

#### Create model

In [7]:
from sklearn.ensemble import RandomForestRegressor
import numpy as np
from sklearn.model_selection import train_test_split

np.random.seed(42)

X = housing_df.drop('target', axis = 1)
y = housing_df['target']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

#### Model evaluation for regression models

In [8]:
model.score(X_test, y_test)

0.8066196804802649

In [9]:
y_test.mean()

np.float64(2.0550030959302323)

##### R^2 score - the coefficient of determination

*  It represents the proportion of variance (of y) that has been explained by the independent variables in the model. It provides an indication of goodness of fit and therefore a measure of how well unseen samples are likely to be predicted by the model, through the proportion of explained variance.

In [11]:
from sklearn.metrics import r2_score

# Fill an array with y_test mean
y_test_mean = np.full(len(y_test), y_test.mean())

In [12]:
y_test_mean[:10]

array([2.0550031, 2.0550031, 2.0550031, 2.0550031, 2.0550031, 2.0550031,
       2.0550031, 2.0550031, 2.0550031, 2.0550031])

In [13]:
r2_score(y_true=y_test,
         y_pred=y_test_mean)

0.0

In [14]:
r2_score(y_true=y_test,
         y_pred=y_test)

1.0

##### Mean absolute error

*   Risk metric corresponding to the expected value of the absolute error loss or l1
-norm loss.

In [15]:
# MAE
from sklearn.metrics import mean_absolute_error

y_preds = model.predict(X_test)
mae = mean_absolute_error(y_true=y_test,
                          y_pred=y_preds)

In [16]:
y_preds

array([0.49384  , 0.75494  , 4.9285964, ..., 4.8363785, 0.71782  ,
       1.67901  ])

In [17]:
y_test

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: target, Length: 4128, dtype: float64

In [18]:
import pandas as pd
df = pd.DataFrame(data={'actual values': y_test,
                        'predicted values': y_preds})
df['differences'] = df['predicted values'] - df['actual values']
df

       actual values  predicted values  differences
20046        0.47700          0.493840     0.016840
3024         0.45800          0.754940     0.296940
15663        5.00001          4.928596    -0.071414
20484        2.18600          2.540290     0.354290
9814         2.78000          2.331760    -0.448240
...              ...               ...          ...
15362        2.63300          2.220380    -0.412620
16623        2.66800          1.947760    -0.720240
18086        5.00001          4.836378    -0.163632
2144         0.72300          0.717820    -0.005180
3665         1.51500          1.679010     0.164010

[4128 rows x 3 columns]

In [19]:
df['differences'].mean()

np.float64(0.0121069218749996)

In [21]:
np.abs(df['differences']).mean()

np.float64(0.3265721842781009)

##### Mean squared error

*   Risk metric corresponding to the expected value of the squared (quadratic) error or loss.

In [22]:
from sklearn.metrics import mean_squared_error

y_preds = model.predict(X_test)
mse = mean_squared_error(y_true=y_test,
                         y_pred=y_preds)
mse

0.2534073069137548

In [24]:
df['squared_differences'] = np.square(df['differences'])
df

       actual values  predicted values  differences  squared_differences
20046        0.47700          0.493840     0.016840             0.000284
3024         0.45800          0.754940     0.296940             0.088173
15663        5.00001          4.928596    -0.071414             0.005100
20484        2.18600          2.540290     0.354290             0.125521
9814         2.78000          2.331760    -0.448240             0.200919
...              ...               ...          ...                  ...
15362        2.63300          2.220380    -0.412620             0.170255
16623        2.66800          1.947760    -0.720240             0.518746
18086        5.00001          4.836378    -0.163632             0.026775
2144         0.72300          0.717820    -0.005180             0.000027
3665         1.51500          1.679010     0.164010             0.026899

[4128 rows x 4 columns]

In [25]:
# Calculate MSE by hand

squared = np.square(df['differences'])
squared.mean()

np.float64(0.2534073069137548)

In [26]:
df.iloc[0]

actual values          0.477000
predicted values       0.493840
differences            0.016840
squared_differences    0.000284
Name: 20046, dtype: float64

In [27]:
df_large_error = df.copy()
df_large_error.iloc[0]['squared_differences'] = 16

/tmp/ipython-input-4161693133.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_large_error.iloc[0]['squared_differences'] = 16

In [28]:
df_large_error.head()

       actual values  predicted values  differences  squared_differences
20046        0.47700          0.493840     0.016840            16.000000
3024         0.45800          0.754940     0.296940             0.088173
15663        5.00001          4.928596    -0.071414             0.005100
20484        2.18600          2.540290     0.354290             0.125521
9814         2.78000          2.331760    -0.448240             0.200919

In [29]:
# Calculate MSE with large error
df_large_error['squared_differences'].mean()

np.float64(0.25728320720794084)

In [30]:
df_large_error.iloc[1:100] = 20
df_large_error.head()

       actual values  predicted values  differences  squared_differences
20046          0.477           0.49384      0.01684                 16.0
3024          20.000          20.00000     20.00000                 20.0
15663         20.000          20.00000     20.00000                 20.0
20484         20.000          20.00000     20.00000                 20.0
9814          20.000          20.00000     20.00000                 20.0

In [31]:
# Calculate MSE with large error
df_large_error['squared_differences'].mean()

np.float64(0.7333540351264799)

### Cross-validation accuracy

In [41]:
https = "https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv"
heart_disease = pd.read_csv(https)
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [43]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop('target', axis=1)
y = heart_disease['target']
clf = RandomForestClassifier(n_estimators=100)

cv_acc = cross_val_score(clf, X, y, cv=5, scoring=None) # if scoring=None, estimator's default scoring evaluation metrics
cv_acc

array([0.81967213, 0.90163934, 0.83606557, 0.78333333, 0.78333333])

In [44]:
# Cross-validated accuracy
print(f"The cross-validated accuracy is: {np.mean(cv_acc) * 100:.2f}%")

The cross-validated accuracy is: 82.48%

In [46]:
np.random.seed(42)

cv_acc = cross_val_score(clf, X, y, cv=5, scoring='accuracy')
cv_acc

array([0.81967213, 0.90163934, 0.83606557, 0.78333333, 0.78333333])

In [47]:
# Cross-validated accuracy
print(f"The cross-validated accuracy is: {np.mean(cv_acc) * 100:.2f}%")

The cross-validated accuracy is: 82.48%

In [50]:
# Precision
np.random.seed(42)
cv_precision = cross_val_score(clf, X, y, cv=5, scoring='precision')
cv_precision

array([0.82352941, 0.93548387, 0.84848485, 0.79411765, 0.76315789])

In [51]:
# Cross-validated precision
print(f"The cross-validated precision is: {np.mean(cv_precision)}")

The cross-validated precision is: 0.8329547346025924

In [52]:
# Recall
np.random.seed(42)
cv_recall = cross_val_score(clf, X, y, cv=5, scoring='recall')
cv_recall

array([0.84848485, 0.87878788, 0.84848485, 0.81818182, 0.87878788])

In [53]:
# Cross-validated recall
print(f"The cross-validated recall is: {np.mean(cv_recall)}")

The cross-validated recall is: 0.8545454545454545

Scoring parameter being used for regression models

In [54]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X = housing_df.drop('target', axis=1)
y = housing_df['target']
model = RandomForestRegressor(n_estimators=100)

In [56]:
np.random.seed(42)
cv_r2 = cross_val_score(model, X, y, cv=3, scoring=None)
np.mean(cv_r2)

np.float64(0.6545756342466266)

In [57]:
# Mean absolute error
np.random.seed(42)
cv_mae = cross_val_score(model, X, y, cv=3, scoring='neg_mean_absolute_error')
cv_mae

array([-0.51752855, -0.4267802 , -0.50633939])

In [58]:
# Mean squared error
np.random.seed(42)
cv_mse = cross_val_score(model, X, y, cv=3, scoring='neg_mean_squared_error')
cv_mse

array([-0.51013593, -0.33368417, -0.54029594])

#### Evaluation metrics as Scikit-Learn functions

https://scikit-learn.org/stable/api/sklearn.metrics.html#classification-metrics

In [60]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

np.random.seed(42)

# Create X & y
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

# split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create model
clf = RandomForestClassifier(n_estimators=100)

# Fit the model
clf.fit(X_train, y_train)

# Make preditions
y_preds = clf.predict(X_test)

# Evaluate the model using evaluation functions
print("Classifie metrics on the test set")
print(f"Accuracy: {accuracy_score(y_true=y_test, y_pred=y_preds) * 100:.2f}%")
print(f"Precision: {precision_score(y_true=y_test, y_pred=y_preds) * 100:.2f}%")
print(f"Recall: {recall_score(y_true=y_test, y_pred=y_preds)}")
print(f"F1: {f1_score(y_true=y_test, y_pred=y_preds)}")

Classifie metrics on the test set
Accuracy: 85.25%
Precision: 84.85%
Recall: 0.875
F1: 0.8615384615384616

In [62]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

np.random.seed(42)

# Create X & y
X = housing_df.drop('target', axis=1)
y = housing_df['target']

# split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create model
clf = RandomForestRegressor(n_estimators=100)

# Fit the model
clf.fit(X_train, y_train)

# Make preditions
y_preds = clf.predict(X_test)

# Evaluate the model using evaluation functions
print("Regression metrics on the test set")
print(f"R2 score: {r2_score(y_true=y_test, y_pred=y_preds)}")
print(f"MAE: {mean_absolute_error(y_true=y_test, y_pred=y_preds)}")
print(f"MSE: {mean_squared_error(y_true=y_test, y_pred=y_preds)}")

Regression metrics on the test set
R2 score: 0.8066196804802649
MAE: 0.3265721842781009
MSE: 0.2534073069137548